title: My Awesome Site
description: My first Jekyll page
baseurl: ""                # leave empty for user/organization site
url: "https://digital-c-fiber.github.io/Digital-C-Fiber-webpage/"  # replace with your GitHub username
theme: minima
markdown: kramdown
